steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/LokeshKvms/repo5.git']

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/gke-flask-app:$SHORT_SHA'
    - './repo5'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/gke-flask-app:$SHORT_SHA'

#kubectl set image deployment/cicd-app flask-app-sha256-1=asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/gke-flask-app:$SHORT_SHA
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/cicd-app'
    - 'flask-app-sha256-1=asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/gke-flask-app:$SHORT_SHA'
  env:
    - 'CLOUDSDK_COMPUTE_REGION=asia-south1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'

options:
  logging: CLOUD_LOGGING_ONLY
